# Generated by Django 5.0.4 on 2024-04-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='artist_name',
        ),
    ]
