# Generated by Django 5.0.4 on 2024-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_rename_name_user_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artist_name',
            new_name='name',
        ),
    ]
