# Generated by Django 5.0.4 on 2024-04-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artwork_slug_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='slug',
        ),
    ]
