# Generated by Django 5.0.4 on 2024-04-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_remove_artwork_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='user',
            new_name='name',
        ),
    ]
