# Generated by Django 5.0.4 on 2024-04-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_rename_user_artwork_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='name',
            new_name='user',
        ),
    ]
