# Generated by Django 4.2.6 on 2024-04-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_rename_name_artwork_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='user',
            new_name='owner',
        ),
    ]
